name: CI
on: [push]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install sphinx sphinxcontrib-napoleon
      - name: 
        run: |
          git config --global user.name "Github Action"
          git config --global user.mail "jeff@reverentengineer.com"
          make GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} publish-docs

