name: CI
on: [push]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install sphinx sphinxcontrib-napoleon
      - name: Build docus
        run: |
          sphinx-build docs/sphinx public
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
