name: CI
on: [push]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install sphinx sphinxcontrib-napoleon
      - name: Run ci.sh
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./ci.sh
